FROM registry.fedoraproject.org/fedora-toolbox:43
# Placing this section here because it should be install and forget
# and I definitely don't want to reinstall those when changing the
# stuff below. They shouldn't be changing though.
RUN dnf -y upgrade \
    && dnf clean all

RUN dnf -y install texlive-scheme-full \
    R \
    racket \
    && dnf clean all

ARG LTEX_LS_PLUS_URL="https://github.com/ltex-plus/ltex-ls-plus/releases/download/18.6.1/ltex-ls-plus-18.6.1-linux-x64.tar.gz"
# ltex-ls-plus for grammar checking
RUN curl -o /tmp/ltex-ls-plus.tar.gz -L ${LTEX_LS_PLUS_URL} \
    && tar -xvf /tmp/ltex-ls-plus.tar.gz  -C /usr/local \
    && ln -s /usr/local/ltex-ls-plus-*/bin/ltex-ls-plus /usr/local/bin/ltex-ls-plus \
    && rm /tmp/ltex-ls-plus.tar.gz

# Core of this image: required stuff for emacs
RUN dnf -y copr enable peterwu/iosevka \
    && dnf -y install \
    emacs-pgtk \
    flatpak-xdg-open \
    gnome-themes-extra \
    google-noto-color-emoji-fonts \
    iosevka-fonts \
    wl-clipboard \
    && dnf clean all

# Language tooling

# C/C++ tooling
RUN dnf -y install \
    clang-tools-extra \
    cmake \
    g++ \
    && dnf clean all

# Python tooling
RUN dnf -y install python-pip \
    && dnf clean all \
    && pip install --no-cache-dir pyright

# Random utils that may change
RUN dnf -y install \
    direnv \
    gdb \
    hunspell-en \
    hunspell-fr \
    locate \
    make \
    pandoc \
    perf \
    stow \
    && dnf clean all
