(deftheme chabam-dark
  "My custom inspired by Oxocarbon and Adwaita dark mode")

(let (
      (chabam-foreground      "#FFFFFF")
      (chabam-background      "#161616")
      (chabam-dark-bg         "#000000")
      (chabam-dark-grey       "#2b2b2b")
      (chabam-grey            "#393939")
      (chabam-light-grey      "#525252")
      (chabam-light-pink      "#FF74B8")
      (chabam-pink            "#FF4297")
      (chabam-green           "#00C15A")
      (chabam-dark-green-bg   "#00815A")
      (chabam-blue            "#00B4FF")
      (chabam-blue-bg         "#405e8e")
      (chabam-light-blue      "#66D1FF")
      (chabam-turquoise       "#00DFDB")
      (chabam-dark-turquoise  "#00C1BB")
      (chabam-purple          "#C693FF")
      (chabam-purple-bg       "#49408e")
      (chabam-dark-blue-bg    "#233C6B")
      (chabam-dark-purple-bg  "#554272")
      (chabam-orange          "#FF6300")
      (chabam-electric-blue   "#0064FF")
      (chabam-red             "#990000")
      (adwaita-black          "#241F31")
      (adwaita-red            "#C01C28")
      (adwaita-green          "#2EC27E")
      (adwaita-yellow         "#F5C211")
      (adwaita-blue           "#1E78E4")
      (adwaita-magenta        "#9841BB")
      (adwaita-cyan           "#0AB9DC")
      (adwaita-grey           "#C0BFBC")
      (adwaita-bright-black   "#5E5C64")
      (adwaita-bright-red     "#ED333B")
      (adwaita-bright-green   "#57E389")
      (adwaita-bright-yellow  "#F8E45C")
      (adwaita-bright-blue    "#51A1FF")
      (adwaita-bright-magenta "#C061CB")
      (adwaita-bright-cyan    "#4FD2FD")
      (adwaita-bright-grey    "#F6F5F4")
      )

  (custom-theme-set-variables
   'chabam-dark
   '(frame-background mode (quote dark)))


  (custom-theme-set-faces
   'chabam-dark
   ;; Generic styling
   `(default                            ((t (:foreground ,chabam-foreground :background ,chabam-background))))
   `(highlight                          ((t (:background ,chabam-purple-bg))))
   `(region                             ((t (:background ,chabam-dark-blue-bg))))
   `(match                              ((t (:background ,chabam-purple-bg))))
   `(secondary-selection                ((t (:background ,chabam-dark-purple-bg))))
   `(mode-line                          ((t (:foreground ,chabam-foreground :background ,chabam-electric-blue))))
   `(mode-line-inactive                 ((t (:foreground ,chabam-light-grey :background ,chabam-dark-bg))))
   `(tab-bar                            ((t (:background ,chabam-dark-bg))))
   `(tab-bar-tab-inactive               ((t (:foreground ,chabam-light-grey :background ,chabam-dark-grey))))
   `(tab-bar-tab                        ((t (:inherit default))))
   `(line-number                        ((t (:foreground ,chabam-light-grey :inherit default))))
   `(line-number-current-line           ((t (:foreground ,chabam-light-pink :inherit default))))
   `(border                             ((t (:foreground ,chabam-dark-bg))))
   `(vertical-border                    ((t (:foreground ,chabam-dark-bg))))
   `(cursor                             ((t (:background ,chabam-pink))))
   `(fringe                             ((t (:background ,chabam-background))))
   `(minibuffer-prompt                  ((t (:foreground ,chabam-purple))))
   `(lazy-highlight                     ((t (:background ,chabam-blue-bg))))
   `(isearch                            ((t (:background ,chabam-purple-bg))))
   `(isearch-fail                       ((t (:background ,chabam-red))))
   `(query-replace                      ((t (:background ,chabam-purple-bg))))
   `(show-paren-match                   ((t (:foreground ,chabam-pink :bold t))))
   `(show-paren-mismatch                ((t (:foreground ,chabam-red :bold t))))
   `(button                             ((t (:foreground ,chabam-blue :underline t))))
   `(warning                            ((t (:foreground ,adwaita-yellow))))
   `(error                              ((t (:foreground ,adwaita-red))))
   `(popup-tip-face                     ((t (:foreground ,chabam-foreground :background ,chabam-dark-bg))))
   `(ansi-color-black                   ((t (:foreground ,adwaita-black))))
   `(ansi-color-red                     ((t (:foreground ,adwaita-red))))
   `(ansi-color-blue                    ((t (:foreground ,adwaita-blue))))
   `(ansi-color-cyan                    ((t (:foreground ,adwaita-cyan))))
   `(ansi-color-green                   ((t (:foreground ,adwaita-green))))
   `(ansi-color-yellow                  ((t (:foreground ,adwaita-yellow))))
   `(ansi-color-magenta                 ((t (:foreground ,adwaita-magenta))))
   `(ansi-color-bright-black            ((t (:foreground ,adwaita-bright-black))))
   `(ansi-color-bright-red              ((t (:foreground ,adwaita-bright-red))))
   `(ansi-color-bright-blue             ((t (:foreground ,adwaita-bright-blue))))
   `(ansi-color-bright-cyan             ((t (:foreground ,adwaita-bright-cyan))))
   `(ansi-color-bright-green            ((t (:foreground ,adwaita-bright-green))))
   `(ansi-color-bright-yellow           ((t (:foreground ,adwaita-bright-yellow))))
   `(ansi-color-bright-magenta          ((t (:foreground ,adwaita-bright-magenta))))

   ;; Help styling
   `(help-key-binding                   ((t (:foreground ,chabam-dark-turquoise :background ,chabam-dark-bg, :bold t))))
   `(trailing-whitespace                ((t (:background ,chabam-red :foreground ,chabam-light-grey))))
   `(whitespace-space                   ((t (:foreground ,chabam-dark-grey))))
   `(whitespace-trailing                ((t (:inherit trailing-whitespace))))
   `(whitespace-indentation             ((t (:inherit whitespace-space))))
   `(whitespace-newline                 ((t (:inherit whitespace-space))))

   `(link                               ((t (:foreground ,chabam-light-blue :underline t))))
   `(visited-link                       ((t (:foreground ,chabam-purple :underline t))))
   `(eldoc-highlight-function-argument  ((t (:inherit isearch :bold t))))

   ;; Programming syntax styling
   `(font-lock-builtin-face             ((t (:foreground ,chabam-purple))))
   `(font-lock-comment-face             ((t (:foreground ,chabam-light-grey))))
   `(font-lock-string-face              ((t (:foreground ,chabam-green))))
   `(font-lock-type-face                ((t (:foreground ,chabam-dark-turquoise))))
   `(font-lock-function-name-face       ((t (:foreground ,chabam-light-blue))))
   `(font-lock-keyword-face             ((t (:foreground ,chabam-purple))))
   `(font-lock-constant-face            ((t (:foreground ,chabam-dark-turquoise))))
   `(font-lock-warning-face             ((t (:foreground ,adwaita-yellow))))
   `(font-lock-number-face              ((t (:foreground ,chabam-orange))))
   `(font-lock-variable-name-face       ((t (:foreground ,chabam-foreground))))
   `(font-lock-variable-use-face        ((t (:foreground ,chabam-light-blue))))
   `(font-lock-function-call-face       ((t (:foreground ,chabam-pink))))
   `(font-lock-property-name-face       ((t (:foreground ,chabam-blue))))
   `(font-lock-property-use-face        ((t (:foreground ,chabam-blue))))
   `(font-lock-escape-face              ((t (:foreground ,chabam-turquoise :bold t))))

   ;; 1st party styling
   `(dired-header                       ((t (:foreground ,chabam-blue))))
   `(dired-directory                    ((t (:foreground ,chabam-dark-turquoise))))
   `(dired-symlink                      ((t (:foreground ,chabam-light-pink))))
   `(dired-marked                       ((t (:background ,chabam-blue-bg))))
   `(dired-mark                         ((t (:foreground ,chabam-background))))
   `(apropos-symbol                     ((t (:foreground ,chabam-pink))))
   `(flymake-error                      ((t (:underline (:style wave :color ,chabam-red)))))
   `(flymake-warning                    ((t (:underline (:style wave :color ,adwaita-yellow)))))
   `(flymake-note                       ((t (:underline (:style wave :color ,chabam-blue)))))
   `(flymake-error-echo                 ((t (:foreground ,adwaita-red))))
   `(flymake-warning-echo               ((t (:foreground ,adwaita-yellow))))
   `(flymake-note-echo                  ((t (:foreground ,chabam-blue))))
   `(eglot-highlight-symbol-face        ((t (:inherit lazy-highlight))))
   `(xref-file-header                   ((t (:foreground ,chabam-green :bold t :underline t))))
   `(compilation-info                   ((t (:foreground ,chabam-turquoise))))

   ;; Org mode
   `(org-block                          ((t (:background ,chabam-dark-bg))))
   `(org-block-begin-line               ((t (:background ,chabam-dark-bg :foreground ,chabam-light-grey))))
   `(org-todo                           ((t (:foreground ,chabam-blue))))
   `(org-done                           ((t (:foreground ,chabam-green))))
   `(org-special-keyword                ((t (:foreground ,chabam-light-grey))))
   `(org-date-selected                  ((t (:background ,chabam-pink))))
   `(org-date                           ((t (:foreground ,chabam-light-pink))))
   `(org-headline-done                  ((t (:foreground ,chabam-light-grey))))
   `(org-level-1                        ((t (:foreground ,chabam-pink))))
   `(org-level-2                        ((t (:foreground ,chabam-purple))))
   `(org-level-3                        ((t (:foreground ,chabam-turquoise))))
   `(org-level-4                        ((t (:foreground ,chabam-orange))))
   `(org-level-6                        ((t (:foreground ,chabam-light-blue))))
   `(org-agenda-structure               ((t (:foreground ,chabam-green))))
   `(org-agenda-done                    ((t (:foreground ,chabam-dark-green-bg))))
   `(org-imminent-deadline              ((t (:foreground ,chabam-purple))))
   `(org-upcoming-deadline              ((t (:foreground ,chabam-turquoise))))
   `(org-upcoming-distant-deadline      ((t (:foreground ,chabam-dark-turquoise))))
   `(org-scheduled                      ((t (:foreground ,chabam-dark-turquoise))))
   `(org-scheduled-today                ((t (:foreground ,chabam-light-pink))))
   `(org-time-grid                      ((t (:foreground ,chabam-light-grey))))


   ;; LaTeX mode
   `(font-latex-bold-face               ((t (:foreground ,chabam-dark-turquoise :bold t))))
   `(font-latex-math-face               ((t (:foreground ,chabam-dark-turquoise))))
   `(font-latex-sedate-face             ((t (:foreground ,chabam-purple))))
   `(font-latex-italic-face             ((t (:foreground ,chabam-dark-turquoise :italic t))))
   `(font-latex-underline-face          ((t (:foreground ,chabam-dark-turquoise :underline t))))
   `(font-latex-string-face             ((t (:foreground ,chabam-green))))
   `(font-latex-warning-face            ((t (:foreground ,chabam-orange))))
   `(font-latex-verbatim-face           ((t (:foreground ,chabam-green))))
   `(font-latex-sectioning-5-face       ((t (:foreground ,chabam-dark-turquoise :bold t))))

   ;; 3rd party styling
   `(vertico-current                    ((t (:background ,chabam-dark-grey))))

   `(completions-common-part            ((t (:foreground ,chabam-dark-turquoise))))

   `(orderless-match-face-0             ((t (:inherit completions-common-part))))
   `(orderless-match-face-1             ((t (:foreground ,chabam-pink))))
   `(orderless-match-face-2             ((t (:foreground ,chabam-blue))))
   `(orderless-match-face-3             ((t (:foreground ,chabam-orange))))

   `(diff-hl-insert                     ((t (:background ,chabam-dark-green-bg :foreground ,chabam-green))))
   `(diff-hl-delete                     ((t (:background ,chabam-red :foreground ,adwaita-red))))
   `(diff-hl-change                     ((t (:background ,adwaita-blue :foreground ,adwaita-bright-blue))))

   `(corfu-bar                          ((t (:background ,chabam-grey))))
   `(corfu-default                      ((t (:foreground ,chabam-foreground :background ,chabam-dark-bg))))
   `(corfu-border                       ((t (:background ,chabam-dark-bg))))
   `(corfu-current                      ((t (:inherit vertico-current))))

   `(embrace-help-pair-face             ((t (:foreground ,chabam-pink))))

   `(aw-background-face                 ((t (:foreground ,chabam-grey))))
   `(aw-leading-char-face               ((t (:foreground ,chabam-pink))))
   ))

(provide-theme 'chabam-dark)
