(deftheme chabam-light
  "My custom inspired by Oxocarbon light mode")

(let (
      (chabam-foreground      "#161616")
      (chabam-background      "#FFFFFF")
      (chabam-dark-bg         "#A0A0A0")
      (chabam-light-grey      "#E0E0E0")
      (chabam-lighter-grey    "#EFEFEF")
      (chabam-grey            "#B6B6B6")
      (chabam-dark-grey       "#A2A2A2")
      (chabam-pink            "#FF74B8")
      (chabam-light-pink      "#FF4297")
      (chabam-green           "#00C15A")
      (chabam-dark-green-bg   "#00815A")
      (chabam-blue            "#0095d6")
      (chabam-light-blue      "#41b2e2")
      (chabam-turquoise       "#02cecb")
      (chabam-dark-turquoise  "#00a8a5")
      (chabam-purple          "#8742d6")
      (chabam-blue-bg         "#ddeaff")
      (chabam-purple-bg       "#d8bfff")
      (chabam-orange          "#FF6300")
      (chabam-electric-blue   "#0064ff")
      (chabam-red             "#FF6666")
      (adwaita-black          "#241f31")
      (adwaita-red            "#c01c28")
      (adwaita-green          "#2ec27e")
      (adwaita-yellow         "#f5c211")
      (adwaita-blue           "#1e78e4")
      (adwaita-magenta        "#9841bb")
      (adwaita-cyan           "#0ab9dc")
      (adwaita-grey           "#c0bfbc")
      (adwaita-bright-black   "#5e5c64")
      (adwaita-bright-red     "#ed333b")
      (adwaita-bright-green   "#57e389")
      (adwaita-bright-yellow  "#f8e45c")
      (adwaita-bright-blue    "#51a1ff")
      (adwaita-bright-magenta "#c061cb")
      (adwaita-bright-cyan    "#4fd2fd")
      (adwaita-bright-grey    "#f6f5f4")
      )
  (custom-theme-set-variables
   'chabam-light
   '(frame-background mode (quote light)))

  (custom-theme-set-faces
   'chabam-light
   ;; Generic styling
   `(default                            ((t (:foreground ,chabam-foreground :background ,chabam-background))))
   `(highlight                          ((t (:background ,chabam-purple-bg))))
   `(region                             ((t (:background ,chabam-lighter-grey))))
   `(match                              ((t (:background ,chabam-purple-bg))))
   `(mode-line                          ((t (:foreground ,chabam-background :background ,chabam-electric-blue))))
   `(mode-line-inactive                 ((t (:foreground ,chabam-dark-bg :background ,chabam-light-grey))))
   `(tab-bar                            ((t (:background ,chabam-light-grey))))
   `(tab-bar-tab-inactive               ((t (:foreground ,chabam-light-grey :background ,chabam-grey))))
   `(tab-bar-tab                        ((t (:inherit default))))
   `(line-number                        ((t (:foreground ,chabam-grey :inherit default))))
   `(line-number-current-line           ((t (:foreground ,chabam-light-pink :inherit default))))
   `(border                             ((t (:foreground ,chabam-dark-bg))))
   `(vertical-border                    ((t (:foreground ,chabam-dark-bg))))
   `(cursor                             ((t (:background ,chabam-light-pink))))
   `(fringe                             ((t (:background ,chabam-background))))
   `(minibuffer-prompt                  ((t (:foreground ,chabam-purple))))
   `(lazy-highlight                     ((t (:background ,chabam-blue-bg))))
   `(isearch                            ((t (:background ,chabam-purple-bg))))
   `(isearch-fail                       ((t (:background ,chabam-red))))
   `(query-replace                      ((t (:background ,chabam-purple-bg))))
   `(show-paren-match                   ((t (:foreground ,chabam-pink :bold t))))
   `(show-paren-mismatch                ((t (:foreground ,chabam-red :bold t))))
   `(button                             ((t (:foreground ,chabam-blue :underline t))))
   `(warning                            ((t (:foreground ,adwaita-yellow))))
   `(error                              ((t (:foreground ,adwaita-red))))
   `(popup-tip-face                     ((t (:foreground ,chabam-foreground :background ,chabam-dark-bg))))
   `(ansi-color-black                   ((t (:foreground ,adwaita-black))))
   `(ansi-color-red                     ((t (:foreground ,adwaita-red))))
   `(ansi-color-blue                    ((t (:foreground ,adwaita-blue))))
   `(ansi-color-cyan                    ((t (:foreground ,adwaita-cyan))))
   `(ansi-color-green                   ((t (:foreground ,adwaita-green))))
   `(ansi-color-yellow                  ((t (:foreground ,adwaita-yellow))))
   `(ansi-color-magenta                 ((t (:foreground ,adwaita-magenta))))
   `(ansi-color-bright-black            ((t (:foreground ,adwaita-bright-black))))
   `(ansi-color-bright-red              ((t (:foreground ,adwaita-bright-red))))
   `(ansi-color-bright-blue             ((t (:foreground ,adwaita-bright-blue))))
   `(ansi-color-bright-cyan             ((t (:foreground ,adwaita-bright-cyan))))
   `(ansi-color-bright-green            ((t (:foreground ,adwaita-bright-green))))
   `(ansi-color-bright-yellow           ((t (:foreground ,adwaita-bright-yellow))))
   `(ansi-color-bright-magenta          ((t (:foreground ,adwaita-bright-magenta))))

   ;; Help styling
   `(help-key-binding                   ((t (:foreground ,chabam-turquoise :background ,chabam-light-grey, :bold t))))
   `(trailing-whitespace                ((t (:background ,chabam-red :foreground ,chabam-light-grey))))
   `(whitespace-space                   ((t (:foreground ,chabam-light-grey))))
   `(whitespace-trailing                ((t (:inherit trailing-whitespace))))
   `(whitespace-indentation             ((t (:inherit whitespace-space))))
   `(whitespace-newline                 ((t (:inherit whitespace-space))))

   `(link                               ((t (:foreground ,chabam-light-blue :underline t))))
   `(visited-link                       ((t (:foreground ,chabam-purple :underline t))))
   `(eldoc-highlight-function-argument  ((t (:inherit isearch :bold t))))

   ;; Programming syntax styling
   `(font-lock-builtin-face             ((t (:foreground ,chabam-purple))))
   `(font-lock-comment-face             ((t (:foreground ,chabam-dark-grey))))
   `(font-lock-string-face              ((t (:foreground ,chabam-green))))
   `(font-lock-type-face                ((t (:foreground ,chabam-dark-turquoise))))
   `(font-lock-function-name-face       ((t (:foreground ,chabam-light-blue))))
   `(font-lock-keyword-face             ((t (:foreground ,chabam-purple))))
   `(font-lock-constant-face            ((t (:foreground ,chabam-dark-turquoise))))
   `(font-lock-warning-face             ((t (:foreground ,adwaita-yellow))))
   `(font-lock-number-face              ((t (:foreground ,chabam-orange))))
   `(font-lock-variable-name-face       ((t (:foreground ,chabam-foreground))))
   `(font-lock-variable-use-face        ((t (:foreground ,chabam-light-blue))))
   `(font-lock-function-call-face       ((t (:foreground ,chabam-pink))))
   `(font-lock-property-name-face       ((t (:foreground ,chabam-blue))))
   `(font-lock-property-use-face        ((t (:foreground ,chabam-blue))))
   `(font-lock-escape-face              ((t (:foreground ,chabam-turquoise :bold t))))

   ;; 1st party styling
   `(dired-header                       ((t (:foreground ,chabam-blue))))
   `(dired-directory                    ((t (:foreground ,chabam-dark-turquoise))))
   `(dired-symlink                      ((t (:foreground ,chabam-light-pink))))
   `(dired-marked                       ((t (:background ,chabam-blue-bg))))
   `(dired-mark                         ((t (:foreground ,chabam-background))))
   `(apropos-symbol                     ((t (:foreground ,chabam-pink))))
   `(flymake-error                      ((t (:underline (:style wave :color ,chabam-red)))))
   `(flymake-warning                    ((t (:underline (:style wave :color ,adwaita-yellow)))))
   `(flymake-note                       ((t (:underline (:style wave :color ,chabam-blue)))))
   `(flymake-error-echo                 ((t (:foreground ,adwaita-red))))
   `(flymake-warning-echo               ((t (:foreground ,adwaita-yellow))))
   `(flymake-note-echo                  ((t (:foreground ,chabam-blue))))
   `(eglot-highlight-symbol-face        ((t (:inherit lazy-highlight))))
   `(xref-file-header                   ((t (:foreground ,chabam-green :bold t :underline t))))
   `(compilation-info                   ((t (:foreground ,chabam-turquoise))))

   ;; Org mode
   `(org-block                          ((t (:background ,chabam-light-grey))))
   `(org-block-begin-line               ((t (:background ,chabam-light-grey :foreground ,chabam-foreground))))

   ;; LaTeX mode
   `(font-latex-bold-face               ((t (:foreground ,chabam-dark-turquoise :bold t))))
   `(font-latex-math-face               ((t (:foreground ,chabam-dark-turquoise))))
   `(font-latex-sedate-face             ((t (:foreground ,chabam-purple))))
   `(font-latex-italic-face             ((t (:foreground ,chabam-dark-turquoise :italic t))))
   `(font-latex-underline-face          ((t (:foreground ,chabam-dark-turquoise :underline t))))
   `(font-latex-string-face             ((t (:foreground ,chabam-green))))
   `(font-latex-warning-face            ((t (:foreground ,chabam-orange))))
   `(font-latex-verbatim-face           ((t (:foreground ,chabam-green))))
   `(font-latex-sectioning-5-face       ((t (:foreground ,chabam-dark-turquoise :bold t))))

   ;; 3rd party styling
   `(vertico-current                    ((t (:background ,chabam-light-grey))))
   `(completions-common-part            ((t (:foreground ,chabam-turquoise))))
   `(orderless-match-face-0             ((t (:inherit completions-common-part))))
   `(orderless-match-face-1             ((t (:foreground ,chabam-pink))))
   `(orderless-match-face-2             ((t (:foreground ,chabam-blue))))
   `(orderless-match-face-3             ((t (:foreground ,chabam-orange))))

   `(diff-hl-insert                     ((t (:foreground ,chabam-dark-green-bg :background ,chabam-green))))
   `(diff-hl-delete                     ((t (:background ,chabam-red :foreground ,adwaita-red))))
   `(diff-hl-change                     ((t (:background ,adwaita-blue :foreground ,adwaita-bright-blue))))

   `(corfu-bar                          ((t (:background ,chabam-grey))))
   `(corfu-default                      ((t (:foreground ,chabam-foreground :background ,chabam-light-grey))))
   `(corfu-border                       ((t (:background ,chabam-light-grey))))
   `(corfu-current                      ((t (:inherit vertico-current :background ,chabam-background))))

   `(embrace-help-pair-face             ((t (:foreground ,chabam-pink))))
   ))

(provide-theme 'chabam-light)
