code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension eamodio.gitlens
code --install-extension James-Yu.latex-workshop
code --install-extension ms-vscode.cpptools
code --install-extension shardulm94.trailing-spaces
code --install-extension vadimcn.vscode-lldb
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzhang.markdown-all-in-one
