export SHELL="/bin/bash"
export TERM="vte-256color"
export BROWSER="firefox"
export EDITOR="nvim"
export PAGER="less"
export SCRIPTS="$HOME/.scripts"
export RUST_BIN="$HOME/.cargo/bin"
export PATH="$PATH:$SCRIPTS:$RUST_BIN"

export TEXINPUTS="~/Cours/Common/Latex:"
