#! /bin/sh
feh /home/chabam/Pictures/wallpaper --bg-scale  /home/chabam/Pictures/wallpaper --bg-scale &
xsetroot -cursor_name left_ptr &
compton &
dropbox &
/home/chabam/.config/polybar/launch.sh &
mpd &
bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bpsc config click_to_focus true

bspc config focused_border_color '#ffffff'
bspc config normal_border_color '#151515'
bspc config presel_feedback_color '#ffffff'
