#! /bin/sh
feh /home/chabam/Pictures/wallpaper --bg-scale  /home/chabam/Pictures/wallpaper --bg-scale &
xsetroot -cursor_name left_ptr &
compton -f --refresh-rate 144 &
/home/chabam/.config/polybar/launch.sh &
mpd &
bspc monitor DVI-I-1 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color '#ffeb3b'
bspc config normal_border_color '#151515'
