#! /bin/sh
feh --bg-scale ~/Pictures/wallpaper &
xsetroot -cursor_name left_ptr &
compton &
dropbox &
mpd &
[[ -z $(pgrep -xU $UID mpdscribble) ]] && mpdscribble &
/home/chabam/.config/polybar/launch.sh &

bspc monitor DVI-D-0 -d I II III IV V
bspc monitor DVI-I-1 -d VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bpsc config click_to_focus true

bspc config focused_border_color '#FF5E8E'
bspc config normal_border_color '#668b9b'
bspc config presel_feedback_color '#FF5E8E'
