FROM registry.fedoraproject.org/fedora-toolbox:44
RUN dnf -y upgrade \
    && dnf clean all

# Placing this section here because it should be install and forget
# and I definitely don't want to reinstall those when changing the
# stuff below. They shouldn't be changing though.
RUN dnf -y install \
    texlive-scheme-medium \
    texlive-collection-latex \
    texlive-collection-latexrecommended \
    texlive-collection-latexextra \
    texlive-collection-fontsrecommended \
    texlive-pgf \
    texlive-e-french \
    texlive-collection-langenglish \
    texlive-collection-langfrench \
    texlive-collection-xetex \
    texlive-collection-luatex \
    R \
    racket-minimal \
    && dnf clean all

WORKDIR /tmp
ARG LTEX_LS_PLUS_VERSION="18.7.0"
ARG LTEX_LS_PLUS_URL="https://github.com/ltex-plus/ltex-ls-plus/releases/download/${LTEX_LS_PLUS_VERSION}/ltex-ls-plus-${LTEX_LS_PLUS_VERSION}-linux-x64.tar.gz"
# ltex-ls-plus for grammar checking
RUN curl -o ltex-ls-plus.tar.gz -L ${LTEX_LS_PLUS_URL} \
    && tar -xvf ltex-ls-plus.tar.gz  -C /usr/local --no-same-owner --no-overwrite-dir \
    && ln -s /usr/local/ltex-ls-plus-*/bin/ltex-ls-plus /usr/local/bin/ltex-ls-plus \
    && rm ltex-ls-plus.tar.gz

# Core of this image: required stuff for emacs
RUN dnf -y install \
    emacs-pgtk \
    flatpak-xdg-open \
    adw-gtk3-theme \
    google-noto-color-emoji-fonts \
    gdk-pixbuf2-modules-extra \
    jetbrains-mono-fonts-all \
    wl-clipboard \
    && dnf clean all

# Mail in Emacs
RUN dnf -y install \
    mu \
    isync \
    msmtp

WORKDIR /tmp
# Installing cyrus-sasl-xoauth2 for oauth authentication
RUN sudo dnf install -y cyrus-sasl-devel automake libtool && \
    git clone https://github.com/moriyoshi/cyrus-sasl-xoauth2 && \
    cd cyrus-sasl-xoauth2/ && \
    ./autogen.sh && \
    ./configure && \
    sudo make install && \
    sudo mv /usr/lib/sasl2/* /usr/lib64/sasl2/ && \
    sudo rmdir /usr/lib/sasl2

WORKDIR /tmp
RUN sudo dnf install -y rustc cargo && \
    git clone https://github.com/ltratt/pizauth && \
    cd pizauth && \
    sudo make install

# Language tooling

# C/C++ tooling
RUN dnf -y install \
    clang-tools-extra \
    cmake \
    g++ \
    bear \
    && dnf clean all

# Python tooling
RUN dnf -y install python-pip \
    && dnf clean all \
    && pip install --no-cache-dir pyright

# Random utils that may change
RUN dnf -y install \
    direnv \
    gdb \
    hunspell-en \
    hunspell-fr \
    enchant2-devel \
    locate \
    make \
    pandoc \
    perf \
    stow \
    && dnf clean all
