(add-to-list 'load-path "~/.config/emacs/lisp" t)

(load "theming")
(load "containerized")
(load "core")
(load "frame-and-windows")
(load "minibuffer-enhancements")
(load "editor-enhancements")
(load "source-control")
(load "ide-like")
(load "interactive-modes")
(load "prog-modes")
(load "org-and-friends")
(load "abbreviations")
