#!/bin/sh 
case $BLOCK_BUTTON in
    1) "$HOME"/.scripts/play-pause ;;  # right click, pause/unpause
esac

pangoify() {
    sed -e "s/\\&/&amp;/g;"
}

spotify=$(playerctl status)
mpc=$(mpc status)
if [ "$spotify" = "Playing" ] || [ "$spotify" = "Paused" ]; then
	if [ "$spotify" = "Paused" ]; then
		status="⏸️"
	else
		status="▶️"
	fi
	artist=$(playerctl metadata artist)
	title=$(playerctl metadata title)
	echo "$status $artist - $title" | pangoify
elif [ "$(echo "$mpc" | grep "paused")" ] || [ "$(echo "$mpc" | grep "playing")" ]; then
	if [ "$(echo "$mpc" | grep "paused")" ]; then
		status="⏸️"
	else
		status="▶️"
	fi
	artisttitle=$(echo "$mpc" | awk 'NR==1')
	echo "$status $artisttitle" | pangoify
else
	echo ""
	exit
fi

