#!/bin/sh 
case $BLOCK_BUTTON in
    1) ~/.scripts/play-pause ;;  # right click, pause/unpause
esac

spotify=$(playerctl status)
mpc=$(mpc status)
if [ "$spotify" = "Playing" ] || [ "$spotify" = "Paused" ]; then
	if [ "$spotify" = "Paused" ]; then
		status="⏸️"
	else
		status="▶️"
	fi
	artist=$(playerctl metadata artist)
	title=$(playerctl metadata title)
	echo "$status $artist - $title"
elif [ "$(echo "$mpc" | grep "paused")" ] || [ "$(echo "$mpc" | grep "playing")" ]; then
	if [ "$(echo "$mpc" | grep "paused")" ]; then
		status="⏸️"
	else
		status="▶️"
	fi
	artisttitle=$(echo "$mpc" | awk 'NR==1')
	echo "$status $artisttitle"
else
	echo ""
	exit
fi

