#!/bin/bash

power_action=$(printf "Log out\nSuspend\nHibernate\nReboot\nPoweroff\nCancel" | rofi -dmenu -p "Select a power action" | tr '[:upper:]' '[:lower:]')

if [ "$power_action" != "cancel" ]
then
    if [ "$power_action" == "log out" ]
    then
        i3-msg exit
        exit
    fi
    systemctl "$power_action"
fi
